---
- name: Install Jenkins
  apt: pkg=jenkins state=latest update_cache=yes
  register: jenkins_install

- name: "{{ delay | default(10) }} second delay while starting Jenkins"
  wait_for: port=8080 delay={{ delay | default(10) }}
  when: jenkins_install.changed

- name: "Create CLI destination directory: {{ jenkins_dest }}"
  file: path={{ jenkins_dest }} state=directory owner=vagrant group=vagrant mode=0644

- name: Get Jenkins CLI to {{ cli_dest }}
  get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest={{ cli_dest }} mode=0440

- name: Get Jenkins updates to {{ updates_dest }}
  get_url: url=http://updates.jenkins-ci.org/update-center.json dest={{ updates_dest }} mode=0440
  register: jenkins_updates

- name: Update-center Jenkins
  shell: "cat {{ updates_dest }} | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- http://localhost:8080/updateCenter/byId/default/postBack"
  when: jenkins_updates.changed
  notify: Restart Jenkins
