---
- name: ensuring add-apt-repository is installed
  apt: pkg=python-software-properties state=latest
 
- name: adding webupd8 ppa for java7 installer
  apt_repository: repo=ppa:webupd8team/java
 
- name: updating apt cache
  apt: update_cache=yes
 
- name: installing java7
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true |
         debconf-set-selections && 
         echo debconf shared/accepted-oracle-license-v1-1 seen true | 
         debconf-set-selections &&
         apt-get -y install oracle-java7-installer

